package sm.dao;

import sm.pojo.JqiComm;

public interface JqiCommMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    int insert(JqiComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    int insertSelective(JqiComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    JqiComm selectByPrimaryKey(Integer commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JqiComm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_comm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JqiComm record);
}