package sm.dao;

import sm.pojo.JqiMenu;

public interface JqiMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    int insert(JqiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    int insertSelective(JqiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    JqiMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JqiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JqiMenu record);
}