package sm.dao;

import sm.pojo.JqiPic;

public interface JqiPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    int insert(JqiPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    int insertSelective(JqiPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    JqiPic selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JqiPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JqiPic record);
}