package sm.dao;

import sm.pojo.JqiTxt;

public interface JqiTxtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer txtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int insert(JqiTxt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int insertSelective(JqiTxt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    JqiTxt selectByPrimaryKey(Integer txtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JqiTxt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JqiTxt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jqi_txt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JqiTxt record);
}