package sm.pojo;

import java.util.Date;

public class JqiComm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_id
     *
     * @mbggenerated
     */
    private Integer commId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_name
     *
     * @mbggenerated
     */
    private String commName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_phone
     *
     * @mbggenerated
     */
    private String commPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_email
     *
     * @mbggenerated
     */
    private String commEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_opinion
     *
     * @mbggenerated
     */
    private String commOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_comm.comm_date
     *
     * @mbggenerated
     */
    private Date commDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_id
     *
     * @return the value of jqi_comm.comm_id
     *
     * @mbggenerated
     */
    public Integer getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_id
     *
     * @param commId the value for jqi_comm.comm_id
     *
     * @mbggenerated
     */
    public void setCommId(Integer commId) {
        this.commId = commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_name
     *
     * @return the value of jqi_comm.comm_name
     *
     * @mbggenerated
     */
    public String getCommName() {
        return commName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_name
     *
     * @param commName the value for jqi_comm.comm_name
     *
     * @mbggenerated
     */
    public void setCommName(String commName) {
        this.commName = commName == null ? null : commName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_phone
     *
     * @return the value of jqi_comm.comm_phone
     *
     * @mbggenerated
     */
    public String getCommPhone() {
        return commPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_phone
     *
     * @param commPhone the value for jqi_comm.comm_phone
     *
     * @mbggenerated
     */
    public void setCommPhone(String commPhone) {
        this.commPhone = commPhone == null ? null : commPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_email
     *
     * @return the value of jqi_comm.comm_email
     *
     * @mbggenerated
     */
    public String getCommEmail() {
        return commEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_email
     *
     * @param commEmail the value for jqi_comm.comm_email
     *
     * @mbggenerated
     */
    public void setCommEmail(String commEmail) {
        this.commEmail = commEmail == null ? null : commEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_opinion
     *
     * @return the value of jqi_comm.comm_opinion
     *
     * @mbggenerated
     */
    public String getCommOpinion() {
        return commOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_opinion
     *
     * @param commOpinion the value for jqi_comm.comm_opinion
     *
     * @mbggenerated
     */
    public void setCommOpinion(String commOpinion) {
        this.commOpinion = commOpinion == null ? null : commOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_comm.comm_date
     *
     * @return the value of jqi_comm.comm_date
     *
     * @mbggenerated
     */
    public Date getCommDate() {
        return commDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_comm.comm_date
     *
     * @param commDate the value for jqi_comm.comm_date
     *
     * @mbggenerated
     */
    public void setCommDate(Date commDate) {
        this.commDate = commDate;
    }
}