package sm.pojo;

import java.util.Date;

public class JqiMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_menu.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_menu.menu_update_date
     *
     * @mbggenerated
     */
    private Date menuUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_menu.menu_type
     *
     * @mbggenerated
     */
    private Integer menuType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_menu.menu_id
     *
     * @return the value of jqi_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_menu.menu_id
     *
     * @param menuId the value for jqi_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_menu.menu_name
     *
     * @return the value of jqi_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_menu.menu_name
     *
     * @param menuName the value for jqi_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_menu.menu_url
     *
     * @return the value of jqi_menu.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_menu.menu_url
     *
     * @param menuUrl the value for jqi_menu.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_menu.menu_update_date
     *
     * @return the value of jqi_menu.menu_update_date
     *
     * @mbggenerated
     */
    public Date getMenuUpdateDate() {
        return menuUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_menu.menu_update_date
     *
     * @param menuUpdateDate the value for jqi_menu.menu_update_date
     *
     * @mbggenerated
     */
    public void setMenuUpdateDate(Date menuUpdateDate) {
        this.menuUpdateDate = menuUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_menu.menu_type
     *
     * @return the value of jqi_menu.menu_type
     *
     * @mbggenerated
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_menu.menu_type
     *
     * @param menuType the value for jqi_menu.menu_type
     *
     * @mbggenerated
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }
}