package sm.pojo;

import java.util.Date;

public class JqiTxt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_txt.txt_id
     *
     * @mbggenerated
     */
    private Integer txtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_txt.txt_position
     *
     * @mbggenerated
     */
    private String txtPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_txt.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_txt.txt_update_date
     *
     * @mbggenerated
     */
    private Date txtUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jqi_txt.txt_detail
     *
     * @mbggenerated
     */
    private String txtDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_txt.txt_id
     *
     * @return the value of jqi_txt.txt_id
     *
     * @mbggenerated
     */
    public Integer getTxtId() {
        return txtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_txt.txt_id
     *
     * @param txtId the value for jqi_txt.txt_id
     *
     * @mbggenerated
     */
    public void setTxtId(Integer txtId) {
        this.txtId = txtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_txt.txt_position
     *
     * @return the value of jqi_txt.txt_position
     *
     * @mbggenerated
     */
    public String getTxtPosition() {
        return txtPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_txt.txt_position
     *
     * @param txtPosition the value for jqi_txt.txt_position
     *
     * @mbggenerated
     */
    public void setTxtPosition(String txtPosition) {
        this.txtPosition = txtPosition == null ? null : txtPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_txt.menu_id
     *
     * @return the value of jqi_txt.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_txt.menu_id
     *
     * @param menuId the value for jqi_txt.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_txt.txt_update_date
     *
     * @return the value of jqi_txt.txt_update_date
     *
     * @mbggenerated
     */
    public Date getTxtUpdateDate() {
        return txtUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_txt.txt_update_date
     *
     * @param txtUpdateDate the value for jqi_txt.txt_update_date
     *
     * @mbggenerated
     */
    public void setTxtUpdateDate(Date txtUpdateDate) {
        this.txtUpdateDate = txtUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jqi_txt.txt_detail
     *
     * @return the value of jqi_txt.txt_detail
     *
     * @mbggenerated
     */
    public String getTxtDetail() {
        return txtDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jqi_txt.txt_detail
     *
     * @param txtDetail the value for jqi_txt.txt_detail
     *
     * @mbggenerated
     */
    public void setTxtDetail(String txtDetail) {
        this.txtDetail = txtDetail == null ? null : txtDetail.trim();
    }
}